name: publeet1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  baseflow_plugin_template: ^2.1.1
  test: ^1.24.1
  fluttertoast: ^8.2.2
  #location
  google_maps_flutter: ^2.2.6
  location: ^4.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  provider: ^6.0.5
#firebase
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
#authentication
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.1

flutter:

  uses-material-design: true

  assets:
   - assets/google.png
   - assets/locations.json
   - assets/publeet1.png
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/publeet_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/publeet_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/publeet_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/publeet_icon.png"